{
    "message": {},
    "error_message": {
        "api": {
            "dot_env_variable_undefined": "La variable no está definida en el archivo .env.",
            "not_defined_env_variable": "La variable %{0} no está definida en el archivo .env.",
            "error_database_initialization": "Error durante la inicialización de la fuente de datos '%{0}'"
        },
        "translate": {
            "wrong_number_of_parameters": "Número incorrecto de parámetros para la clave %{0}. Se esperaban %{1}, se obtuvieron %{2}"
        },
        "http": {
            "success": "La operación de solicitud se ha procesado correctamente.",
            "created": "La operación de creación se ha procesado correctamente.'",
            "no_content": "Sin contenido.",
            "bad_request": "Solicitud incorrecta.",
            "argument": "Argumento incorrecto.",
            "unauthorized": "No autorizado.",
            "forbidden": "Prohibido.",
            "not_found": "No encontrado.",
            "already_exists": "Ya existe.",
            "internal_server_error": "Error interno del servidor.",
            "critical_server_error": "Error crítico.",
            "Forbidden": "error_message.http.Forbidden"
        },
        "password": {
            "failed_encrypt": "No se pudo cifrar la contraseña.",
            "failed_verify": "No se pudo verificar la contraseña."
        },
        "application": {
            "there_is_not_application_with_id": "No existe aplicación con la identificación: %{0}.",
            "application_with_id_not_found": "No se encontró aplicación con la identificación: %{0}.",
            "could_not_associate_application_and_user": "No se pudo asociar la aplicación %{0} y el usuario con el nombre de usuario %{1}."
        },
        "user": {
            "already_exist_user_same_password": "Ya existe un usuario con el mismo nombre de usuario.'",
            "could_not_created_user_with_username": "No se pudo crear el usuario con el nombre de usuario: %{0}.",
            "user_with_id_not_found": "No se encontró el usuario con la identificación: %{0}.",
            "user_with_username_not_found": "No se encontró el usuario con el nombre de usuario %{0}.",
            "could_not_update_user": "No se pudo actualizar el usuario con el nombre de usuario: %{0}"
        },
        "group_link": {
            "group_link_with_id_not_found": "No se encontró el enlace de grupo con la identificación: %{0}."
        },
        "link": {
            "wrong_name_argument": "Argumento de nombre incorrecto.",
            "wrong_url_argument": "Argumento de URL incorrecto."
        }
    }
}
